COMPLETE_GRAPH = 'COMPLETE_GRAPH'
COMPLETE_BIPARTITE_GRAPH = 'COMPLETE_BIPARTITE_GRAPH'
STAR_GRAPH = 'STAR_GRAPH'
CYCLE_GRAPH = 'CYCLE_GRAPH'
WHEEL_GRAPH = 'WHEEL_GRAPH'
PATH_GRAPH = 'PATH_GRAPH'
HYPERCUBE_GRAPH = 'HYPERCUBE_GRAPH'

SPECIAL_CLASS_GRAPHS = (
    COMPLETE_GRAPH,
    COMPLETE_BIPARTITE_GRAPH,
    STAR_GRAPH,
    CYCLE_GRAPH,
    WHEEL_GRAPH,
    PATH_GRAPH,
    HYPERCUBE_GRAPH
)

SPECIAL_CLASS_GRAPH_NAMES = (
    (COMPLETE_GRAPH, 'completo$%s$'),
    (COMPLETE_BIPARTITE_GRAPH, 'bipartido_completo$%s$'),
    (STAR_GRAPH, 'estrela$%s$'),
    (CYCLE_GRAPH, 'ciclo$%s$'),
    (WHEEL_GRAPH, 'roda$%s$'),
    (PATH_GRAPH, 'caminho$%s$'),
    (HYPERCUBE_GRAPH, 'ncubo$%s$'),
)
